#!/bin/sh
[ "$ACTION" = add ] || exit 0
VIDPID="${PRODUCT%%/*}"
case "$PRODUCT" in
  1286/4e3c/*|2c7c/6026/*)
    logger -t modem-bind "Binding EC200x class modem ($PRODUCT)"
    echo 1 > /sys/bus/usb/devices/$DEVPATH/authorized
    ;;
esac
